<?php
ob_start();
	$title = 'Mon portfolio';
?>
<main id="home" class="container">
	<section class="language">
		<h2>Mes réalisation en PHP</h2>
		<a class="model" href="/luhn">
			<header class="model-head">
				<h3 class="model-title">Algoritme de Luhn</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/luhn.png" class="" width="100%" alt="Ilustration de l'algoritme de Luhn">
			</div>
		</a>

		<a class="model" href="/calendar">
			<header class="model-head">
				<h3 class="model-title">Un calendrier</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/calendar.png" class="" width="100%" alt="Ilustration du calendrier">
			</div>
		</a>

		<a class="model" href="/game">
			<header class="model-head">
				<h3 class="model-title">Mini jeu</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/game.png" class="" width="100%" alt="Ilustration du mini jeu">
			</div>
		</a>

	</section>

	<section class="language">
		<h2>Mes réalisation en JavaScript</h2>
		<a class="model" href="/snake">
			<header class="model-head">
				<h3 class="model-title">Snake</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/snake.png" class="" width="100%" alt="Ilustration de snake">
			</div>
		</a>

		<a class="model" href="/slider">
			<header class="model-head">
				<h3 class="model-title">Slider</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/slider.png" class="" width="100%" alt="Ilustration du slider">
			</div>
		</a>

		<a class="model" href="/search">
			<header class="model-head">
				<h3 class="model-title">Barre de recherche</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/search.png" class="" width="100%" alt="Ilustration de la barre de recherche">
			</div>
		</a>
	</section>

	<section class="language">
		<h2>Mes réalisation en HTML5/CSS3</h2>
		
		<a class="model" href="/responsive">
			<header class="model-head">
				<h3 class="model-title">Responsive web design</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/responsive.png" class="" width="100%" alt="Ilustration du responsive web design">
			</div>
		</a>
	</section>
</main>
<?php
$content = ob_get_clean();
include('../views/template/template.phtml');
?>
