<?php
ob_start();
	$title = 'Mon portfolio';
?>
<main id="home" class="container">
	<section class="language">
		<h2>Mes réalisation en PHP</h2>
		<a class="model" href="/luhn">
			<header class="model-head">
				<h3 class="model-title">Algoritme de Luhn</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/luhn.png" class="" width="100%" alt="Miniature">
			</div>
		</a>
	</section>

	<section class="language">
		<h2>Mes réalisation en JavaScript</h2>
		<a class="model" href="/snake">
			<header class="model-head">
				<h3 class="model-title">Snake</h3>
			</header>
			<div class="model-content">
				<img src="../images/mini/luhn.png" class="" width="100%" alt="Miniature">
			</div>
		</a>
	</section>
</main>
<?php
$content = ob_get_clean();
include('../views/template/template.phtml');
?>
