<?php
ob_start();
	$title = 'Effet parallaxe';
?>
<span id="s1"></span>
<span id="s2"></span>
<span id="s3"></span>
<main id="wrap" class="">
	<ul id="nav">
		<li><a href="#s1">Slide 1</a></li>
		<li><a href="#s2">Slide 2</a></li>
		<li><a href="#s3">Slide 3</a></li>
	</ul>

	<div id="slide1">
		<div class="slide_inside">					
			<h1 class="display-1">Le grand canyon <br>du colorado</h1>
		</div>
	</div>
	
	<div id="slide2">
		<div class="slide_inside">
			<h2>Slide 2</h2>
			<p>
				Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore eveniet laboriosam dolor asperiores beatae 
				quia reiciendis explicabo, totam iste nemo labore! Nemo consequuntur amet dolorum consectetur ipsum quaerat 
				tempore impedit.
			</p>
		</div>
	</div>

	<div id="slide3">
		<div class="slide_inside">
			<h2>Slide 3</h2>
				<p>
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate totam 
					repellat eius cupiditate laboriosam soluta officiis suscipit sunt, veniam consequuntur, 
					repudiandae explicabo deleniti ut expedita. Natus rem reprehenderit labore, harum a ullam atque 
					magni voluptatem ut distinctio, veritatis eveniet! Nulla exercitationem mollitia, amet excepturi 
					aut sed ut? Sunt id possimus iure veritatis iusto recusandae omnis nihil nisi accusamus, similique 
					nulla illum illo dicta cumque iste voluptatibus numquam laboriosam pariatur adipisci itaque! Culpa, 
					voluptas iusto? Magnam excepturi, quibusdam nihil veniam inventore quos eveniet explicabo esse omnis 
					repudiandae aspernatur animi numquam consequatur nulla tempora perspiciatis corporis, placeat doloribus 
					sunt, a quam minus!
				</p>
		</div>
	</div>
</main>
<?php
$content = ob_get_clean();
include('../views/template/template.phtml');
?>
