<?php
ob_start();
	$title = 'Slider';
?>
<main id="" class="container">
	<h2><?= $title; ?></h2>

	<div class="slideshow">
		<ul>
			<li><img src="images/slider/slide1.jpeg" alt="" width="1200" height="400" /></li>
			<li><img src="images/slider/slide2.jpeg" alt="" width="1200" height="400" /></li>
			<li><img src="images/slider/slide3.jpeg" alt="" width="1200" height="400" /></li>
			<li><img src="images/slider/slide4.jpeg" alt="" width="1200" height="400" /></li>
		</ul>
	</div>
	
</main>
<?php
$content = ob_get_clean();
include('../views/template/template.phtml');
?>
