<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="/home">
		<h1>
			<img src="../images/logo/logo2.png" class="d-inline-block align-top" width="48" height="48"
			alt="Logo:portfolio goupy.eu">
			Mon portfolio
		</h1>
	</a>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse justify-content-end"  id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="/luhn">Luhn</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/calendar">Calendrier</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/game">Jeu</a>
			</li>

			<li class="nav-item separator"></li>

			<li class="nav-item">
				<a class="nav-link" href="/snake">Snake</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/slider">Slider</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/search">Recherche</a>
			</li>

			<li class="nav-item separator"></li>

			<li class="nav-item">
				<a class="nav-link" href="/responsive">Responsive</a>
			</li>
		</ul>
	</div>
</nav>
